"""Embed the repository schema for offline file:// use. Run after schema changes."""
import json
import re
import importlib.util
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
schema = json.loads((ROOT / "docs/tenriff-skin.schema.json").read_text(encoding="utf-8-sig"))
example = json.loads((ROOT / "examples/skins/TenRiff-Example/skin.json").read_text(encoding="utf-8-sig"))
payload = {"schema": schema, "example": example}
# Share the client's original vector geometry with the offline canvas preview.
sys.dont_write_bytecode = True
spec = importlib.util.spec_from_file_location('menu_vectors', ROOT / 'tools/generate_native_menu_assets.py')
vectors = importlib.util.module_from_spec(spec)
spec.loader.exec_module(vectors)
payload["menuVectors"] = {name.lower(): shapes for name, shapes in vectors.ASSETS.items()}
# The native catalog is optional so older source packages can still regenerate.
native = ROOT / "skins/TenRiff_NativeEditable/skin.json"
if native.exists():
    payload["native"] = json.loads(native.read_text(encoding="utf-8-sig"))
gameplay_catalog = ROOT / "assets/native-gameplay/luma-keys/editor-catalog.json"
if gameplay_catalog.exists():
    payload["gameplayNative"] = json.loads(gameplay_catalog.read_text(encoding="utf-8-sig"))
    # Read the actual client palettes; the web preview must not invent alternate defaults.
    config = (ROOT / "src/config/Config.cpp").read_text(encoding="utf-8-sig")
    colors = dict(re.findall(r'\{"(\w+)", "\w+", 0x([0-9A-Fa-f]{6})\}', config))
    start = config.index('default_skin_lane_color_map()')
    block = config[start:config.index('return kDefaults;', start)]
    payload["gameplayNative"]["palettes"] = {
        mode: ['#' + colors[token] for token in re.findall(r'"(\w+)"', values)]
        for mode, values in re.findall(r'\{"([0-9k+]+)",\s*\{([^}]+)\}', block)
    }
text = "/* Generated by sync_catalog.py; no network requests. */\n"
text += "(function(root){const data=" + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
text += "if(typeof module==='object'&&module.exports)module.exports=data;else root.TenRiffCatalog=data;\n})(typeof globalThis!=='undefined'?globalThis:this);\n"
(HERE / "catalog.js").write_text(text, encoding="utf-8")
print("Wrote offline schema and example to catalog.js")
