"""Original Luma Keys UI vectors; one source for editable SVGs and cached D2D sprites.

All geometry is authored here, with no third-party art or runtime file dependency.
Run --check to verify that generated assets match their source.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def layer(x, y, w, h, color, mix=1., alpha=1., radius=0.):
    return (x, y, w, h, int(color, 16), mix, alpha, radius)


def key(lit):
    rows = [layer(0, 0, 128, 256, '071017', radius=9),
            layer(2, 1, 124, 250, 'E3F6FF', .48 if lit else .18, radius=8),
            layer(4, 4, 120, 243, '122634', .40 if lit else .69, radius=7)]
    # Broad satin surface, narrow bevels: recognisable even on sixteen lanes.
    for i in range(24):
        rows.append(layer(7, 8 + i * 8, 114, 9, 'E6FAFF' if lit else '2A3A48',
                          (.37 - i * .009) if lit else (.30 + i * .020)))
    rows += [layer(7, 7, 114, 4, 'FFFFFF', .78, .9 if lit else .65, 1),
             layer(5, 14, 2, 206, 'EFFAFF', .7, .38 if lit else .16),
             layer(121, 14, 2, 206, '020A12', .9, .8),
             layer(9, 199, 110, 2, '07101C', .95, .7),
             layer(10, 204, 108, 34, '06111B', .88, .9, 3),
             layer(17, 215, 94, 3, 'D6FFFF', .65, .95 if lit else .32, 1),
             layer(17, 222, 56, 2, '83FFF0', .4, .68 if lit else .13),
             layer(15, 238, 98, 3, '02070D', 1., .85, 1)]
    for i in range(3):
        rows.append(layer(52 + i * 9, 32, 4, 4, 'E5FFFF', .7, .88 if lit else .22, 1))
    return rows


def note(hold=False, tail=False):
    rows = [layer(0, 0, 128, 32, '050C17', 1, 1, 4),
            layer(1, 1, 126, 29, 'DDF9FF', .48, 1, 3),
            layer(3, 4, 122, 22, '172F45', .15, 1, 2),
            layer(4, 4, 120, 8, 'F3FFFF', .76, .95, 1),
            layer(4, 12, 120, 5, 'D6FAFF', .34),
            layer(4, 22, 120, 4, '010913', .50),
            layer(7, 27, 114, 2, 'E8FFFF', .88, .95),
            layer(8, 14, 3, 6, 'FFFFFF', .9, .75),
            layer(117, 14, 3, 6, 'FFFFFF', .9, .75)]
    if hold:
        rows += [layer(53, 13, 22, 8, '091725', .9, .8, 1),
                 layer(59, 14, 3, 6, 'FFFFFF', .9),
                 layer(66, 14, 3, 6, 'FFFFFF', .9)]
    if tail:
        rows += [layer(18, 13, 92, 6, '081320', .94, .8, 1)]
    return rows


ASSETS = {'KeyIdle': (128, 256, key(False)), 'KeyLit': (128, 256, key(True)),
          'Note': (128, 32, note()), 'HoldHead': (128, 32, note(hold=True)),
          'HoldTail': (128, 32, note(tail=True))}
PALETTES = {'pearl': 0xF6F8FF, 'ice': 0x4F80FF, 'mint': 0x72EBCB}


def mixed(lane, base, amount):
    return '#'+''.join(f'{round(((lane >> bit) & 255) * (1-amount) + ((base >> bit) & 255) * amount):02x}' for bit in (16, 8, 0))


def outputs():
    header = ['// Generated by tools/generate_luma_keys_assets.py. Edit the generator.',
              '#pragma once', '#include <array>', '#include <cstdint>',
              'namespace tenriff::render::luma_keys_assets {',
              'struct Layer { float x, y, width, height; uint32_t color; float mix, alpha, radius; };']
    out = {}
    for name, (width, height, rows) in ASSETS.items():
        header.append(f'inline constexpr std::array<Layer, {len(rows)}> k{name}{{{{')
        for x, y, w, h, color, mix, alpha, radius in rows:
            header.append(f'    {{{x:.3f}f, {y:.3f}f, {w:.3f}f, {h:.3f}f, 0x{color:06X}u, {mix:.4f}f, {alpha:.4f}f, {radius:.3f}f}},')
        header.append('}};')
        for palette, lane in PALETTES.items():
            svg = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">']
            for x, y, w, h, color, mix, alpha, radius in rows:
                svg.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{radius}" fill="{mixed(lane,color,mix)}" opacity="{alpha}"/>')
            out[ROOT / 'assets/native-gameplay/luma-keys' / f'{name.lower()}-{palette}.svg'] = '\n'.join(svg+['</svg>'])+'\n'
    header.append('} // namespace tenriff::render::luma_keys_assets')
    out[ROOT / 'src/render/LumaKeysAssets.h'] = '\n'.join(header)+'\n'
    return out


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, text in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != text: stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8', newline='\n')
    if stale: raise SystemExit('Stale Luma Keys assets: '+', '.join(stale))
    print('Luma Keys: 15 original SVGs and the compiled sprite atlas '+('verified' if args.check else 'generated'))
