"""Original vector artwork for TenRiff's native menu. Python standard library only.

One geometry source exports editable SVGs and a compiled C++ atlas, so packaged
clients need no loose files, image decoders, network requests or working directory.
Run --check to detect stale generated files without changing anything.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# 100 x 100 local coordinates; each polyline carries its own color and fill mode.
# Studio symbols use one 100-unit grid and the same optical stroke weight.
# Legacy names remain available to imported skins. New option symbols describe
# the action itself: lanes, key mapping, swatches, a timer, a person and a check.
INK = "ECF6FF"

def line(*points):
    return (INK, False, list(points))

def solid(*points):
    return (INK, True, list(points))

def box(left, top, right, bottom):
    return line((left, top), (right, top), (right, bottom), (left, bottom), (left, top))

ASSETS = {
    "Mark": [solid((8,20),(70,20),(58,34),(44,34),(28,80),(10,80),(26,34),(8,34)),
             solid((76,20),(94,20),(72,80),(54,80))],
    "Prism": [line((50,12),(84,32),(84,68),(50,88),(16,68),(16,32),(50,12)),
              line((16,32),(50,52),(84,32)), line((50,52),(50,88))],
    "Chevron": [line((34,20),(64,50),(34,80))],
    "Spark": [line((50,20),(50,80)), line((20,50),(80,50))],
    "Wave": [line((12,50),(26,50),(34,30),(46,70),(58,22),(70,58),(78,50),(88,50))],
    "Audio": [line((16,38),(32,38),(50,22),(50,78),(32,62),(16,62),(16,38)),
              line((62,36),(70,44),(70,56),(62,64)), line((74,24),(86,38),(86,62),(74,76))],
    "Display": [box(12,18,88,68), line((50,68),(50,82)), line((32,82),(68,82))],
    "Input": [line((50,82),(50,20)), line((40,30),(50,20),(60,30)),
              line((50,62),(28,48),(28,32)), box(22,22,34,32),
              line((50,70),(74,54),(74,42)), box(68,32,80,42)],
    "Network": [box(38,14,62,34), box(12,66,36,86), box(64,66,88,86),
                line((50,34),(50,50),(24,50),(24,66)), line((50,50),(76,50),(76,66))],
    "Sliders": [line((16,26),(36,26)),box(36,18,48,34),line((48,26),(84,26)),
                line((16,50),(60,50)),box(60,42,72,58),line((72,50),(84,50)),
                line((16,74),(28,74)),box(28,66,40,82),line((40,74),(84,74))],
    "Folder": [line((12,32),(12,20),(38,20),(48,32),(88,32),(88,80),(12,80),(12,32),(88,32))],
    "Exit": [line((44,18),(18,18),(18,82),(44,82)), line((38,50),(84,50)),
             line((68,34),(84,50),(68,66))],
    "Keys": [box(14,18,86,82), line((32,18),(32,82)), line((50,18),(50,82)),
             line((68,18),(68,82)),solid((17,58),(29,58),(29,64),(17,64)),
             solid((35,38),(47,38),(47,44),(35,44)),solid((53,58),(65,58),(65,64),(53,64)),
             solid((71,28),(83,28),(83,34),(71,34))],
    "Keymap": [box(12,26,88,76),box(24,38,34,48),box(44,38,54,48),box(64,38,74,48),
               line((28,62),(72,62))],
    "Skin": [box(16,16,44,44),box(56,16,84,44),box(16,56,44,84),
             solid((56,56),(84,56),(84,84),(56,84))],
    "Latency": [line((40,12),(60,12)),line((50,12),(50,22)),
                line((36,24),(64,24),(80,40),(80,66),(64,82),(36,82),(20,66),(20,40),(36,24)),
                line((50,34),(50,54),(66,54)),line((72,26),(80,18))],
    "Profile": [line((40,18),(60,18),(70,28),(70,44),(60,54),(40,54),(30,44),(30,28),(40,18)),
                line((16,84),(16,72),(32,62),(68,62),(84,72),(84,84),(16,84))],
    "Keytest": [box(14,18,86,82),line((30,50),(44,64),(72,34))],
}

def outputs():
    points, paths, ranges = [], [], []
    files = {}
    for name, shapes in ASSETS.items():
        first = len(paths)
        svg = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">',
               f'  <title>TenRiff native menu - {name}</title>']
        for color, filled, vertices in shapes:
            paths.append((len(points), len(vertices), color, filled))
            points.extend(vertices)
            tag = 'polygon' if filled else 'polyline'
            svg.append(f'  <{tag} points="' + ' '.join(f'{x},{y}' for x, y in vertices) +
                       f'" fill="{"#" + color if filled else "none"}" stroke="#{color}" '
                       'stroke-width="2.16" stroke-linejoin="miter" stroke-linecap="butt"/>')
        svg.append('</svg>')
        files[ROOT / 'assets' / 'native-menu' / (name.lower() + '.svg')] = '\n'.join(svg) + '\n'
        ranges.append((name, first, len(shapes)))
    header = ['// Generated by tools/generate_native_menu_assets.py. Edit the generator.', '#pragma once',
              '#include <array>', '#include <cstdint>', 'namespace tenriff::render::native_menu_assets {',
              'struct Point { float x, y; };',
              'struct Path { unsigned first, count; uint32_t color; bool filled; };',
              'struct Asset { unsigned first, count; };',
              f'inline constexpr std::array<Point, {len(points)}> points{{{{']
    header += [f'    {{{x}.0f, {y}.0f}},' for x, y in points]
    header += ['}};', f'inline constexpr std::array<Path, {len(paths)}> paths{{{{']
    header += [f'    {{{first}, {count}, 0x{color}, {str(filled).lower()}}},' for first, count, color, filled in paths]
    header += ['}};'] + [f'inline constexpr Asset k{name}{{{first}, {count}}};' for name, first, count in ranges]
    header += ['} // namespace tenriff::render::native_menu_assets', '']
    files[ROOT / 'src' / 'render' / 'NativeMenuAssets.h'] = '\n'.join(header)
    return files

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    if stale:
        raise SystemExit('Stale native menu assets: ' + ', '.join(stale))
    print(f'Native menu atlas: {len(ASSETS)} assets; {"verified" if args.check else "generated"}.')

if __name__ == '__main__':
    main()
