"""Original vector artwork for TenRiff's native menu. Python standard library only.

One geometry source exports editable SVGs and a compiled C++ atlas, so packaged
clients need no loose files, image decoders, network requests or working directory.
Run --check to detect stale generated files without changing anything.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# 100 x 100 local coordinates; each polyline carries its own color and fill mode.
ASSETS = {
    "Mark": [("63E9F2", True, [(8, 20), (70, 20), (58, 34), (44, 34), (28, 80), (10, 80), (26, 34), (8, 34)]),
             ("A499FF", True, [(76, 20), (94, 20), (72, 80), (54, 80)])],
    "Prism": [("63E9F2", False, [(50, 3), (88, 27), (78, 75), (50, 97), (12, 72), (22, 25), (50, 3), (50, 97)]),
              ("A499FF", False, [(22, 25), (78, 75), (12, 72), (88, 27), (22, 25)]),
              ("ECF6FF", False, [(12, 72), (50, 3), (78, 75)])],
    "Chevron": [("63E9F2", False, [(25, 16), (62, 50), (25, 84)]),
                ("A499FF", False, [(48, 16), (85, 50), (48, 84)])],
    "Spark": [("ECF6FF", True, [(50, 4), (59, 41), (96, 50), (59, 59), (50, 96), (41, 59), (4, 50), (41, 41)])],
    "Wave": [("63E9F2", False, [(3, 50), (19, 50), (27, 25), (39, 80), (53, 12), (65, 65), (74, 42), (81, 50), (97, 50)])],
    "Audio": [("63E9F2", False, [(10, 39), (29, 39), (51, 20), (51, 80), (29, 61), (10, 61), (10, 39)]),
              ("A499FF", False, [(65, 33), (73, 42), (73, 58), (65, 67)]),
              ("A499FF", False, [(78, 20), (90, 37), (90, 63), (78, 80)])],
    "Display": [("63E9F2", False, [(10, 15), (90, 15), (90, 69), (10, 69), (10, 15)]),
                ("A499FF", False, [(50, 69), (50, 85), (27, 85), (73, 85)])],
    "Input": [("63E9F2", False, [(7, 25), (93, 25), (93, 77), (7, 77), (7, 25)]),
              ("A499FF", False, [(22, 43), (31, 43), (31, 51), (22, 51), (22, 43)]),
              ("A499FF", False, [(44, 43), (53, 43), (53, 51), (44, 51), (44, 43)]),
              ("A499FF", False, [(66, 43), (75, 43), (75, 51), (66, 51), (66, 43)]),
              ("63E9F2", False, [(30, 64), (69, 64)])],
    "Network": [("63E9F2", False, [(50, 17), (84, 72), (16, 72), (50, 17)]),
                ("A499FF", False, [(50, 17), (50, 51), (84, 72), (50, 51), (16, 72)])],
    "Sliders": [("63E9F2", False, [(12, 25), (88, 25)]), ("A499FF", False, [(12, 50), (88, 50)]),
                ("63E9F2", False, [(12, 75), (88, 75)]), ("ECF6FF", False, [(32, 16), (32, 34)]),
                ("ECF6FF", False, [(67, 41), (67, 59)]), ("ECF6FF", False, [(44, 66), (44, 84)])],
    "Folder": [("63E9F2", False, [(8, 29), (8, 17), (39, 17), (49, 29), (91, 29), (91, 82), (8, 82), (8, 29), (91, 29)])],
    "Exit": [("A499FF", False, [(46, 14), (16, 14), (16, 86), (46, 86)]),
             ("63E9F2", False, [(35, 50), (87, 50), (69, 31), (87, 50), (69, 69)])],
}

def outputs():
    points, paths, ranges = [], [], []
    files = {}
    for name, shapes in ASSETS.items():
        first = len(paths)
        svg = ['<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">',
               f'  <title>TenRiff native menu - {name}</title>']
        for color, filled, vertices in shapes:
            paths.append((len(points), len(vertices), color, filled))
            points.extend(vertices)
            tag = 'polygon' if filled else 'polyline'
            svg.append(f'  <{tag} points="' + ' '.join(f'{x},{y}' for x, y in vertices) +
                       f'" fill="{"#" + color if filled else "none"}" stroke="#{color}" '
                       'stroke-width="2" stroke-linejoin="round" stroke-linecap="round"/>')
        svg.append('</svg>')
        files[ROOT / 'assets' / 'native-menu' / (name.lower() + '.svg')] = '\n'.join(svg) + '\n'
        ranges.append((name, first, len(shapes)))
    header = ['// Generated by tools/generate_native_menu_assets.py. Edit the generator.', '#pragma once',
              '#include <array>', '#include <cstdint>', 'namespace tenriff::render::native_menu_assets {',
              'struct Point { float x, y; };',
              'struct Path { unsigned first, count; uint32_t color; bool filled; };',
              'struct Asset { unsigned first, count; };',
              f'inline constexpr std::array<Point, {len(points)}> points{{{{']
    header += [f'    {{{x}.0f, {y}.0f}},' for x, y in points]
    header += ['}};', f'inline constexpr std::array<Path, {len(paths)}> paths{{{{']
    header += [f'    {{{first}, {count}, 0x{color}, {str(filled).lower()}}},' for first, count, color, filled in paths]
    header += ['}};'] + [f'inline constexpr Asset k{name}{{{first}, {count}}};' for name, first, count in ranges]
    header += ['} // namespace tenriff::render::native_menu_assets', '']
    files[ROOT / 'src' / 'render' / 'NativeMenuAssets.h'] = '\n'.join(header)
    return files

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    if stale:
        raise SystemExit('Stale native menu assets: ' + ', '.join(stale))
    print(f'Native menu atlas: {len(ASSETS)} assets; {"verified" if args.check else "generated"}.')

if __name__ == '__main__':
    main()
